/*
 * This file was generated by m-servicefwgen
 * Command line was: m-servicefwgen -c UploadEngineProxy -p uploadengineproxy UploadEngine-9894.xm
 *
 * m-servicefwgen is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef UPLOADENGINEPROXY_H_1364581203
#define UPLOADENGINEPROXY_H_1364581203

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.meego.sharing.webuploadengine
 */
class UploadEngineProxy: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.meego.sharing.webuploadengine"; }

public:
    UploadEngineProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~UploadEngineProxy();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<bool> newUpload(const QString &path)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(path);
        return asyncCallWithArgumentList(QLatin1String("newUpload"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  namespace meego {
    namespace sharing {
      typedef ::UploadEngineProxy webuploadengine;
    }
  }
}
#endif
